name: to_do_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_screenutil: ^5.5.4
  date_picker_timeline: ^1.2.3
  sqflite: ^2.1.0+1
  path: ^1.8.2
#  flutter_alarm_clock: ^0.0.2
#  flutter_local_notifications: ^12.0.2
  fluttertoast: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/todo_icon.png

  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product Sans Bold.ttf
        - asset: assets/fonts/Product Sans Bold Italic.ttf
        - asset: assets/fonts/Product Sans Italic.ttf
        - asset: assets/fonts/Product Sans Regular.ttf
          style: italic